#!/usr/bin/env python3
"""
Merge multiple 3D building models into a single OBJ file.
This script combines all PLY files from the 3DOM reconstruction into one unified model.
"""

import os
import argparse
import numpy as np
import logging
from pathlib import Path
import sys

log_level = os.environ.get("LOGLEVEL", "INFO").upper()
log_format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logging.basicConfig(
    level=getattr(logging, log_level), 
    format=log_format,
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)
logger.info(f"Merge: Initialisation avec niveau de log: {log_level}")


def read_ply_file(ply_path):
    """
    Read a PLY file and return vertices and faces.
    Handles both ASCII and binary PLY formats.
    
    Returns:
        vertices: numpy array of shape (N, 3) with vertex coordinates
        faces: list of face indices
    """
    vertices = []
    faces = []
    
    # Binary/ ASCII
    with open(ply_path, 'rb') as f:
        header_lines = []
        is_binary = False
        
        while True:
            line = f.readline()
            if not line:
                break
            
            try:
                line_str = line.decode('utf-8').strip()
            except UnicodeDecodeError:
                break
                
            header_lines.append(line_str)
            
            if 'format binary' in line_str:
                is_binary = True
            elif line_str == 'end_header':
                break
    
    if is_binary:
        try:
            import trimesh
            mesh = trimesh.load(ply_path)
            if hasattr(mesh, 'vertices') and hasattr(mesh, 'faces'):
                return mesh.vertices, mesh.faces.tolist()
            else:
                logger.warning(f"Could not load mesh data from {ply_path}")
                return np.array([]), []
        except ImportError:
            logger.warning(f"Skipping binary PLY file {ply_path} (trimesh not available)")
            return np.array([]), []
        except Exception as e:
            logger.warning(f"Error loading binary PLY file {ply_path}: {e}")
            return np.array([]), []
    
    # Handle ASCII PLY files
    try:
        with open(ply_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        logger.error(f"Could not decode PLY file {ply_path}")
        return np.array([]), []
    
    # Parse PLY header
    vertex_count = 0
    face_count = 0
    in_header = True
    vertex_start = 0
    face_start = 0
    
    
    for i, line in enumerate(lines):
        line = line.strip()
        if in_header:
            if line.startswith('element vertex'):
                vertex_count = int(line.split()[-1])
            elif line.startswith('element face'):
                face_count = int(line.split()[-1])
            elif line == 'end_header':
                in_header = False
                vertex_start = i + 1
                face_start = vertex_start + vertex_count
                break
    
    # Read vertices
    for i in range(vertex_start, vertex_start + vertex_count):
        if i < len(lines):
            parts = lines[i].strip().split()
            if len(parts) >= 3:
                x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
                vertices.append([x, y, z])
    
    # Read faces
    for i in range(face_start, face_start + face_count):
        if i < len(lines):
            parts = lines[i].strip().split()
            if len(parts) >= 4:
                num_vertices = int(parts[0])
                if num_vertices == 3 and len(parts) >= 4:
                    face_indices = [int(parts[j]) for j in range(1, 4)]
                    faces.append(face_indices)
                elif num_vertices == 4 and len(parts) >= 5:
                    face_indices = [int(parts[j]) for j in range(1, 5)]
                    faces.append([face_indices[0], face_indices[1], face_indices[2]])
                    faces.append([face_indices[0], face_indices[2], face_indices[3]])
    
    return np.array(vertices), faces


def write_obj_file(obj_path, all_vertices, all_faces, building_names=None):
    """
    Write vertices and faces to an OBJ file.
    
    Args:
        obj_path: Output OBJ file path
        all_vertices: Combined vertices from all models
        all_faces: Combined faces from all models (already with adjusted indices)
        building_names: Optional list of building names for groups
    """
    with open(obj_path, 'w') as f:
        f.write("# Merged 3D building models\n")
        f.write("# Generated by CITYZEN pipeline\n\n")
        

        for vertex in all_vertices:
            f.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        
        f.write("\n")
        
        for i, faces in enumerate(all_faces):
            if building_names and i < len(building_names):
                f.write(f"g {building_names[i]}\n")
            
            for face in faces:
                face_indices = [str(idx + 1) for idx in face]
                f.write(f"f {' '.join(face_indices)}\n")
        
        f.write("\n")


def write_ply_file(output_path, vertices, all_faces, building_names=None):
    """
    Write merged geometry to PLY file format.
    
    Args:
        output_path: Path to output PLY file
        vertices: Combined vertices array
        all_faces: List of face arrays for each building
        building_names: Optional list of building names for comments
    """
    total_faces = sum(len(faces) for faces in all_faces)
    
    with open(output_path, 'w') as f:
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"comment Merged 3D building models\n")
        if building_names:
            f.write(f"comment Buildings: {', '.join(building_names)}\n")
        f.write(f"element vertex {len(vertices)}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        f.write(f"element face {total_faces}\n")
        f.write("property list uchar int vertex_indices\n")
        f.write("end_header\n")
        
        for vertex in vertices:
            f.write(f"{vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        
        for faces in all_faces:
            for face in faces:
                face_indices = [str(idx) for idx in face]
                f.write(f"{len(face)} {' '.join(face_indices)}\n")


def merge_3d_models(models_dir, output_path, ply_only=False):
    """
    Merge all PLY files in the models directory into a single OBJ file.
    
    Args:
        models_dir: Directory containing PLY files
        output_path: Path for the merged OBJ file
        ply_only: If True, only generate PLY output
    """
    
    models_dir = Path(models_dir)
    output_path = Path(output_path)
    
    ply_files = list(models_dir.glob("*.ply"))
    
    if not ply_files:
        logger.warning(f"No PLY files found in {models_dir}")
        return False
    
    logger.info(f"Found {len(ply_files)} PLY files to merge")
    
    all_vertices = []
    all_faces = []
    building_names = []
    vertex_offset = 0
    
    for ply_file in sorted(ply_files):
        logger.debug(f"Processing {ply_file.name}")
        
        try:
            vertices, faces = read_ply_file(ply_file)
            
            if len(vertices) == 0:
                logger.warning(f"No vertices found in {ply_file.name}")
                continue
            
            adjusted_faces = []
            for face in faces:
                adjusted_face = [idx + vertex_offset for idx in face]
                adjusted_faces.append(adjusted_face)
            
            all_vertices.append(vertices)
            all_faces.append(adjusted_faces)
            building_names.append(ply_file.stem)
            
            vertex_offset += len(vertices)
            
            logger.debug(f"  - {len(vertices)} vertices, {len(faces)} faces")
            
        except Exception as e:
            logger.error(f"Error processing {ply_file.name}: {e}")
            continue
    
    if not all_vertices:
        logger.error("No valid models found to merge")
        return False
    
    combined_vertices = np.vstack(all_vertices)
    
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if not ply_only:
        logger.info(f"Writing merged model to {output_path}")
        write_obj_file(output_path, combined_vertices, all_faces, building_names)
    
    ply_output = output_path.with_suffix('.ply')
    logger.info(f"Writing merged PLY model to {ply_output}")
    write_ply_file(ply_output, combined_vertices, all_faces, building_names)
    
    total_vertices = len(combined_vertices)
    total_faces = sum(len(faces) for faces in all_faces)
    
    logger.info(f"Merged model created successfully:")
    logger.info(f"  - {len(ply_files)} buildings")
    logger.info(f"  - {total_vertices} total vertices")
    logger.info(f"  - {total_faces} total faces")
    if not ply_only:
        logger.info(f"  - OBJ Output: {output_path}")
    logger.info(f"  - PLY Output: {ply_output}")
    
    return True


def main():
    parser = argparse.ArgumentParser(description="Merge 3D building models into a single OBJ file")
    parser.add_argument("--models_dir", required=True, help="Directory containing PLY model files")
    parser.add_argument("--output", required=True, help="Output OBJ file path")
    parser.add_argument("--ply-only", action="store_true", help="Only generate PLY output (not OBJ)")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose logging")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.models_dir):
        logger.error(f"Models directory not found: {args.models_dir}")
        return 1
    
    success = merge_3d_models(args.models_dir, args.output, args.ply_only)
    
    return 0 if success else 1


if __name__ == "__main__":
    exit(main())
